### ISSUE TITLE
Accessing

### ISSUE THREAD

**Issue by MonziTech** [jamiegau/cinema-catcher-app#3]
Hi, 
when I try to access to D-Cine via browser I see the right page, but login take me to a double error

![Cinema-catcher error01](https://user-images.githubusercontent.com/130071603/232491171-ab7258e8-23f5-4bb3-bbf9-344b9843181b.png)

Thank you for your time...

**Comment by jamiegau** [comment]
Umm...
The software is crashing out in the background.
To give me a idea of what's happening.

Got to the `/opt/cinema-catcher-app` directory
After making the error happen again
type the command `sudo docker compose logs > error.log`, to dump the logs to a file. `error.log`
Post the file here so I can have a look.

**Comment by MonziTech** [comment]
Today I repeated (for the n-th time) the steps after the `docker compose pull` command and this time I was able to log in by browser (I had also requested and received the Activation code).
Now my question is: the command sequence after the download 
![image](https://user-images.githubusercontent.com/130071603/232758938-040aea8a-5986-4046-9389-3a7beb073d71.png)
are "permanent" or I have to repeat them at every system reboot?

(Sorry if I ask dumby questions, I'm not used to play with linux...)

**Comment by jamiegau** [comment]
Those commands are needed for the INITIAL setup, specifically the `migrate` command as it does the initial database setup.
The `catcher_setup` command makes sure template data (Like the admin login user) has been created etc.  Plus it does consistency checks on the database.

The `update.sh` command actually runs them again as it applies any database upgrades, and setup applies any new consistency checks and data upgrades/modifications needed due to the upgrade.   You can run them multiple times without issue.

But as I mentioned they have to run by hand initially on installation before the application will start.
